# Context

The objective is to understand the data that we have! These are the results of this first EDA

### Target variable

1. Credit_Score:
- It has three values, GOOD STANDARD AND POOR, 
- We will change this as a binary classification in orer to build a score
- The distribution does not change through time

### Identifiers

- 100,000 rows
- 12,500 unique clients
- 8 months (JAN - AUG)
- Panel data structure
- There are null names
- We have corrputed SSN as '#F%$D@*&8'
- No duplicated rows

- *Tasks*:
- Convert the months into numbers to split the data temporally
- Ignore identifiers for now that does not provide important informationl ike name ssn,


### CATEGORICAL VARIABLES

1. Occupation:
- There is a wide distribution of occupations, but one of those is empty! no values detected
2. Type of loan:
- The most annoying feature haha, it has different types of loan in the same value, it needs a whole process of transformation
- Also it has 11% of null values, it is important to consider if we should delete them, or treat them as not specified (or learn of the same client in other periods)
3. Credit mix:
- it has null values in the form of '-', and it represent 20% of the data! 
- we can consider to delete this variable or if is possible to populate the null values with the same value of each costumer in the inmediate previous period
4. Payment behavior:
- Almost good but there null values in the form of '!@9#%8', neverthelles they represent only 8%!
5. Payment of min amount:
- Almost good again but we have an important number of cases of NM, a category that probably express null values (not requested, not mentioned)
- Check if the variable is stable through months!

### NUMERICAL VARIABLES

1. Age
- Convert age from strings to int and clean the values with '_'
- Clean outliers and non sense values (thing if we should take them as null values, erros, the best action here is to take the corresponding age of the client in other months)
2. Annual Income:
- Convert the colum from string to float and clean the values with '_'
- It seems accurate, in cleaning check if the monthly salary corresponds to the annual income
3. Monthly Inhand Salary:
- Already float, high null percentage (15%)
- Does not correspond always to the annual income, check for correlation
4. Num bank accounts:
- Already float, with meaningless values to fix (outliers too)
5. Interest rate:
 - Already int, seems well but with outliers to fix
6. Num of loan
 - Needed convertion from string to int, and a cleaning of _ values
 - non sense values like negative number of loans and extreme values
7. Delay from due date:
- Seems to be fine, normal range and alraedy in int type
8. Changed creidt limit:
 - Needed transformation from object to float , but replaceing '_' values to '0' (or not? check before)
 - This feature probably means the % of how the credit limit has changed for each client, it seems to be constant each month..
9. Number of credit inquires:
 - No negative values but with a small % of null values, already int! Just check overhigh values
10. Outsanding Debt:
 - Indicates the total amoutnn of money that the borrower still owe to the lender, INCLUDING the principal plus the interests!
 - Same problem with the '_' values, needed string to float convertion
11. Credit utilizaiton ratio
 - Important variable, it seems clean
12. Credit history age:
 - Importat variable, but with nulls and in a text formatting it needs a parse function
 - It also has nulls, but given that we know the information of other months we can reconstruct the nulls!
13. Total EMI per month:
 - Important feature as well, but maybe correlated with others , it seems to be clean, maybe with outliers
14.  Amount invested :
 - Needed the same transformation, str to float with cleaning _
 - It seems to be free of non sense values
15. Monthly_Balance
 - Same transformation, str to float with cleaning of _
 - Terrible non sense values to clean!

16. Num of delayed payment:
 - Same transformation, str to float with cleaning of _
 - Non sense values detectedm

# Libraries

In [262]:
import kagglehub
import pandas as pd
from kagglehub import KaggleDatasetAdapter

pd.set_option("display.max_columns", None)
pd.options.display.float_format = "{:,.2f}".format
import os

# Functions

In [263]:
def fast_feature_description(feature):

    print("------- NULL VALUES --------")
    print(feature.isna().sum())
    print(feature.isna().mean())

    print("------- INFO -------")
    print(feature.info())

    print("------- Common values -------")
    print(feature.unique().shape)
    print(feature.unique())

# Loading data

In [264]:
train_df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS, "parisrohan/credit-score-classification", "train.csv"
)

test_df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS, "parisrohan/credit-score-classification", "test.csv"
)

/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_5105/3638771850.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  train_df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

/Users/luisfernandocorcueraleon/Desktop/code/Credit-Score-Classification/.venv/lib/python3.9/site-packages/kagglehub/pandas_datasets.py:91: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(
/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_5105/3638771850.py:5: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  test_df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [265]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

In [266]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        50000 non-null  object
 1   Customer_ID               50000 non-null  object
 2   Month                     50000 non-null  object
 3   Name                      44985 non-null  object
 4   Age                       50000 non-null  object
 5   SSN                       50000 non-null  object
 6   Occupation                50000 non-null  object
 7   Annual_Income             50000 non-null  object
 8   Monthly_Inhand_Salary     42502 non-null  float64
 9   Num_Bank_Accounts         50000 non-null  int64
 10  Num_Credit_Card           50000 non-null  int64
 11  Interest_Rate             50000 non-null  int64
 12  Num_of_Loan               50000 non-null  object
 13  Type_of_Loan              44296 non-null  object
 14  Delay_from_due_date       50000 non-null  int64
 15  Num_of_Delayed_Payment    46502 non-null  object
 16  Changed_Credit_Limit      50000 non-null  object
 17  Num_Credit_Inquiries      48965 non-null  float64
 18  Credit_Mix                50000 non-null  object
 19  Outstanding_Debt          50000 non-null  object
 20  Credit_Utilization_Ratio  50000 non-null  float64
 21  Credit_History_Age        45530 non-null  object
 22  Payment_of_Min_Amount     50000 non-null  object
 23  Total_EMI_per_month       50000 non-null  float64
 24  Amount_invested_monthly   47729 non-null  object
 25  Payment_Behaviour         50000 non-null  object
 26  Monthly_Balance           49438 non-null  object
dtypes: float64(4), int64(4), object(19)
memory usage: 10.3+ MB

# Exploring the dataset - identifiers

In [267]:
print(train_df.shape)
train_df.head()

(100000, 28)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,"1,824.84",3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,11.27,4.00,_,809.98,26.82,22 Years and 1 Months,No,49.57,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,NaN,11.27,4.00,Good,809.98,31.94,NaN,No,49.57,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,_,4.00,Good,809.98,28.61,22 Years and 3 Months,No,49.57,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,4,6.27,4.00,Good,809.98,31.38,22 Years and 4 Months,No,49.57,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,"1,824.84",3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,NaN,11.27,4.00,Good,809.98,24.80,22 Years and 5 Months,No,49.57,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [268]:
train_df["Credit_Score"].value_counts(normalize=True)

Credit_Score
Standard   0.53
Poor       0.29
Good       0.18
Name: proportion, dtype: float64

In [269]:
train_df["Customer_ID"].unique().size

12500

In [270]:
print(train_df["Month"].unique())

['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August']

In [271]:
train_df.groupby("Month").size()

Month
April       12500
August      12500
February    12500
January     12500
July        12500
June        12500
March       12500
May         12500
dtype: int64

In [272]:
train_df["SSN"].unique().size

12501

In [273]:
train_df["Name"].unique().size

10140

In [274]:
train_df.groupby("Customer_ID")["SSN"].nunique().sort_values(ascending=False).head(10)

Customer_ID
CUS_0x6da9    2
CUS_0x544     2
CUS_0x5430    2
CUS_0x542f    2
CUS_0x542c    2
CUS_0xa088    2
CUS_0xa08b    2
CUS_0x5413    2
CUS_0x540e    2
CUS_0xa09c    2
Name: SSN, dtype: int64

In [275]:
train_df[train_df["Customer_ID"] == "CUS_0x6da9"]

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
77328,0x1db1a,CUS_0x6da9,January,Davidw,32,353-08-1853,_______,85426.68,"7,024.89",3,6,5,0,NaN,11,9,1.91,3.00,Good,1187.02,28.89,29 Years and 11 Months,No,0.00,70.71242566502217,!@9#%8,871.7765743349779,Standard
77329,0x1db1b,CUS_0x6da9,February,Davidw,32,#F%$D@*&8,Manager,85426.68,"7,024.89",3,6,5,0,NaN,7,9,1.91,3.00,Good,1187.02,32.40,30 Years and 0 Months,No,0.00,326.3287023669127,Low_spent_Medium_value_payments,656.1602976330872,Standard
77330,0x1db1c,CUS_0x6da9,March,Davidw,32_,353-08-1853,Manager,85426.68,"7,024.89",3,6,5,0,NaN,11,NaN,1.91,3.00,Good,1187.02,41.06,30 Years and 1 Months,No,0.00,__10000__,Low_spent_Large_value_payments,329.09595320745325,Standard
77331,0x1db1d,CUS_0x6da9,April,Davidw,33,353-08-1853,Manager,85426.68,"7,024.89",3,6,5,0,NaN,11,9,1.91,3.00,_,1187.02,34.45,30 Years and 2 Months,No,0.00,__10000__,Low_spent_Medium_value_payments,388.3133568992598,Standard
77332,0x1db1e,CUS_0x6da9,May,Davidw,33,#F%$D@*&8,Manager,85426.68,"7,024.89",3,6,5,0,NaN,11,9,5.91,3.00,Good,1187.02,38.71,30 Years and 3 Months,No,0.00,455.40288905313264,High_spent_Small_value_payments,507.0861109468674,Standard
77333,0x1db1f,CUS_0x6da9,June,Davidw,33,353-08-1853,_______,85426.68,"7,024.89",3,6,5,0,NaN,11,9,-1.09,3.00,Good,1187.02,26.03,30 Years and 4 Months,No,0.00,448.3418078088855,Low_spent_Small_value_payments,544.1471921911145,Standard
77334,0x1db20,CUS_0x6da9,July,Davidw,33,353-08-1853,Manager,85426.68,"7,024.89",3,6,5,0,NaN,11,9_,-1.09,3.00,Good,1187.02,32.38,30 Years and 5 Months,No,0.00,454.88672005971495,Low_spent_Medium_value_payments,527.602279940285,Standard
77335,0x1db21,CUS_0x6da9,August,Davidw,33,#F%$D@*&8,Manager,85426.68,"7,024.89",3,6,5,0_,NaN,11,9,1.91,3.00,_,1187.02,27.74,30 Years and 6 Months,NM,0.00,856.9792955447119,Low_spent_Small_value_payments,135.50970445528807,Standard

In [276]:
a = train_df[train_df["Customer_ID"] == "CUS_0x6da9"]["Monthly_Inhand_Salary"].sum()
b = 85426.68 / 7024.89
b

12.160571909311034

In [277]:
train_df[train_df["SSN"] == "#F%$D@*&8"].shape

(5572, 28)

In [278]:
train_df.duplicated().sum()

np.int64(0)

In [279]:
# essential identifiers:

ids = ["Customer_ID", "num_month"]

In [280]:
month_mapping = {
    "January": 202201,
    "February": 202202,
    "March": 202203,
    "April": 202204,
    "May": 202205,
    "June": 202206,
    "July": 202207,
    "August": 202208,
}

train_df["num_month"] = train_df["Month"].map(month_mapping)

train_df["num_month"].value_counts()

num_month
202201    12500
202202    12500
202203    12500
202204    12500
202205    12500
202206    12500
202207    12500
202208    12500
Name: count, dtype: int64

# Target variable

In [281]:
target = "Credit_Score"

counts = train_df[target].value_counts()
percentages = train_df[target].value_counts(normalize=True) * 100

summary = pd.DataFrame({"counts": counts, "%": percentages})
summary

              counts     %
Credit_Score
Standard       53174 53.17
Poor           28998 29.00
Good           17828 17.83

In [282]:
pd.crosstab(train_df["num_month"], train_df[target], normalize="index")

Credit_Score  Good  Poor  Standard
num_month
202201        0.16  0.29      0.56
202202        0.16  0.28      0.56
202203        0.16  0.28      0.56
202204        0.19  0.29      0.52
202205        0.18  0.30      0.52
202206        0.19  0.30      0.51
202207        0.19  0.29      0.52
202208        0.19  0.29      0.52

# Numeric variables

In [283]:
numeric_variables = [
    "Age",
    "Annual_Income",
    "Monthly_Inhand_Salary",
    "Num_Bank_Accounts",
    "Interest_Rate",
    "Num_of_Loan",
    "Delay_from_due_date",
    "Changed_Credit_Limit",
    "Num_Credit_Inquiries",
    "Outstanding_Debt",
    "Credit_Utilization_Ratio",
    "Credit_History_Age",
    "Total_EMI_per_month",
    "Amount_invested_monthly",
    "Monthly_Balance",
    "Num_of_Delayed_Payment",
]

len(numeric_variables)

16

In [284]:
train_df[numeric_variables]

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Interest_Rate,Num_of_Loan,Delay_from_due_date,Changed_Credit_Limit,Num_Credit_Inquiries,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Num_of_Delayed_Payment
0,23,19114.12,"1,824.84",3,3,4,3,11.27,4.00,809.98,26.82,22 Years and 1 Months,49.57,80.41529543900253,312.49408867943663,7
1,23,19114.12,NaN,3,3,4,-1,11.27,4.00,809.98,31.94,NaN,49.57,118.28022162236736,284.62916249607184,NaN
2,-500,19114.12,NaN,3,3,4,3,_,4.00,809.98,28.61,22 Years and 3 Months,49.57,81.699521264648,331.2098628537912,7
3,23,19114.12,NaN,3,3,4,5,6.27,4.00,809.98,31.38,22 Years and 4 Months,49.57,199.4580743910713,223.45130972736786,4
4,23,19114.12,"1,824.84",3,3,4,6,11.27,4.00,809.98,24.80,22 Years and 5 Months,49.57,41.420153086217326,341.48923103222177,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,39628.99,"3,359.42",4,7,2,23,11.5,3.00,502.38,34.66,31 Years and 6 Months,35.10,60.97133255718485,479.87,7
99996,25,39628.99,"3,359.42",4,7,2,18,11.5,3.00,502.38,40.57,31 Years and 7 Months,35.10,54.18595028760385,496.65,7
99997,25,39628.99,"3,359.42",4,5729,2,27,11.5,3.00,502.38,41.26,31 Years and 8 Months,35.10,24.02847744864441,516.81,6
99998,25,39628.99,"3,359.42",4,7,2,20,11.5,3.00,502.38,33.64,31 Years and 9 Months,35.10,251.67258219721603,319.16,NaN
99999,25,39628.99_,"3,359.42",4,7,2,18,11.5,3.00,502.38,34.19,31 Years and 10 Months,35.10,167.1638651610451,393.67,6

## Age

In [285]:
print(train_df["Age"].isna().sum())
print(train_df["Age"].isna().mean())
train_df["Age"].info()

0
0.0
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Age
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB

In [286]:
print(train_df["Age"].unique().shape)

train_df["Age"].unique()

(1788,)

array(['23', '-500', '28_', ..., '4808_', '2263', '1342'], dtype=object)

In [287]:
train_df["Age"] = train_df["Age"].str.replace("_", "")
train_df["Age"] = train_df["Age"].astype(int)

In [288]:
train_df["Age"].describe()

count   100,000.00
mean        110.65
std         686.24
min        -500.00
25%          24.00
50%          33.00
75%          42.00
max       8,698.00
Name: Age, dtype: float64

## Annual Income

In [289]:
fast_feature_description(train_df["Annual_Income"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Annual_Income
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(18940,)
['19114.12' '34847.84' '34847.84_' ... '20002.88' '39628.99' '39628.99_']

In [290]:
print(train_df["Annual_Income"].unique().shape)

train_df["Annual_Income"].unique()

(18940,)

array(['19114.12', '34847.84', '34847.84_', ..., '20002.88', '39628.99',
       '39628.99_'], dtype=object)

In [291]:
train_df["Annual_Income"] = train_df["Annual_Income"].str.replace("_", "")

In [292]:
train_df["Annual_Income"] = train_df["Annual_Income"].astype(float)

In [293]:
train_df["Annual_Income"].describe()

count      100,000.00
mean       176,415.70
std      1,429,618.05
min          7,005.93
25%         19,457.50
50%         37,578.61
75%         72,790.92
max     24,198,062.00
Name: Annual_Income, dtype: float64

## Monthly_Inhand_Salary

In [294]:
fast_feature_description(train_df["Monthly_Inhand_Salary"])

------- NULL VALUES --------
15002
0.15002
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Monthly_Inhand_Salary
Non-Null Count  Dtype
--------------  -----
84998 non-null  float64
dtypes: float64(1)
memory usage: 781.4 KB
None
------- Common values -------
(13236,)
[1824.84333333           nan 3037.98666667 ... 3097.00833333 1929.90666667
 3359.41583333]

In [295]:
train_df["Monthly_Inhand_Salary"].describe()

count   84,998.00
mean     4,194.17
std      3,183.69
min        303.65
25%      1,625.57
50%      3,093.75
75%      5,957.45
max     15,204.63
Name: Monthly_Inhand_Salary, dtype: float64

In [296]:
train_df["avg_salary"] = train_df["Annual_Income"] / train_df["Monthly_Inhand_Salary"]
train_df["avg_salary"].describe()

count   84,998.00
mean        67.24
std        846.10
min          8.09
25%         11.55
50%         12.03
75%         12.55
max     54,110.52
Name: avg_salary, dtype: float64

## Num bank accounts

In [297]:
fast_feature_description(train_df["Num_Bank_Accounts"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Num_Bank_Accounts
Non-Null Count   Dtype
--------------   -----
100000 non-null  int64
dtypes: int64(1)
memory usage: 781.4 KB
None
------- Common values -------
(943,)
[   3    2    1    7    4    0    8    5    6    9   10 1414 1231   67
  572 1488   91  528 1647 1696 1338  649  889 1668  685  857  975 1496
 1534 1620   37 1388 1429 1332 1588  120 1777 1096  803  494  744 1139
  831 1613  741  121  665 1748 1644  823 1356 1651   87  711  450  210
 1671 1722  648  672 1662 1495  510  666  429 1131 1434  980 1026  526
  718 1300 1312 1315  501 1566  480 1042  322  628 1016  333 1265  791
  427  563  905 1190 1036 1611   38  619  555 1769  280  752 1201  812
 1487  222  212 1019 1222  610 1714 1308  525 1158 1115 1616  754 1601
  797 1577  521  703  933  959  809 1089 1656 1113 1715  964 1533 1789
  871  434 1295  565 1724  603  677  541  698 1101  464 1539 1462 1011
 1257 1727   45  244 1266  897  535  484  331  675  826  946 1675  105
 1327  845  549  473  710  527  908   68 1628  371  445 1168  868  687
  455 1003   26 1526  618  598  351 1342 1783  683 1557 1335  416 1747
  137 1475  373  338  942  170  973 1605 1478  386 1448 1033 1225  596
 1731 1214 1481 1105  580  347  108  148 1001 1467 1114 1000  632  246
 1032 1394  689  482 1303  720  574  588 1358  650  708  179  844 1140
  335   60  732 1494 1436  820   28 1576  818  794  731  534  556  691
 1197 1155 1255 1763  769 1124  819  318 1418  882   61  264  194 1798
  611  840  505 1110  719 1065  195  584  550 1014 1022  903  976   31
  417 1423 1148  616  786 1424   55 1061 1293  342   43 1540  488 1122
 1274 1075  722 1268   41  814 1564 1390 1141  497  224 1135  441  374
   74  314 1408  475 1015  681 1236   59 1425 1637 1240  299 1657 1123
 1091 1264 1561 1632 1562  305 1318 1217 1699 1070  864 1391  112  860
  595  229 1624 1051  821 1794 1565  397 1368 1353  508 1725 1413 1239
  847 1317  570   -1  302  456  198  122  832  167 1547 1666 1241  275
  566 1779  201  334 1169  834 1174 1040  530 1676 1468 1093  706  489
 1592  688  830 1784 1543 1600 1178  228  483 1501  950  548  870 1211
  604  804  129  540 1702 1636 1680 1443 1252  499  180  702  885 1652
  795  938  833 1654 1793  303 1621 1516 1138   32  160 1491   83  423
  928  339  931  243 1756  583 1695  274  955  430 1247  490  726  987
   42 1626 1470 1739  887  211  385 1221  753  324  406 1677 1567  785
  182 1079  184 1771 1048 1069  561  589 1634   70 1371  647 1153  239
  801 1279 1287  425 1589  929 1511 1765 1047 1005 1337  981 1766  805
 1574 1638  186   99  288 1650  974  996 1595 1594  865  203 1440  448
  285   94  875  916 1733  240  330   79   82  135 1043  142 1235 1569
 1741 1461  560 1551  409  418 1017  892  354  124  935  313 1363  232
 1200 1184 1432 1479 1407 1080 1719 1024  970  761  158  312 1060  684
  696 1520 1352 1502  936  485  350 1560 1166 1013   34 1691  715 1570
 1751 1503 1194 1558  411  298  260  308  796 1442  912 1256  746  435
  620 1774 1181 1323  837  307 1430   53 1447  259  921  328 1034  353
  822  654  829  609  166  136  172 1306 1028  808  270 1072  514  156
 1331 1630  462 1310 1210  265   50 1355  394 1393  226  991  368 1018
 1037  627 1744  523  894  944 1730 1076 1094 1617  449  678 1164   30
  817 1568  607  709 1230  606 1480   29 1522 1670   49  626 1641 1712
 1370 1782  119 1137 1277   35  947  851 1041 1583 1536  575  196  143
   33  383   57  621  230  162  352 1504 1250   39  511 1364  918 1665
  734 1320  316  771  705 1435  304  116 1553  424  493 1530 1195 1604
  624 1599  782 1606 1622 1285  657 1275 1291 1402  420  932  468  442
 1145   93 1218  283  292  927 1711 1422  364 1398  594  789 1350  676
  216 1012 1426  717 1095 1786  850  777  375  356  701 1325  290 1775
  467 1365 1549  848 1453   84 1458  888  770 1591  582   40 1261 1764
 1067  145  471  476 1128  967  622  641  539  858  295 1395 1517 1297
 1126  926  157 1377  993  125  340  271 1669  272  979  707  564  997
  447 1578 1465  415  714 1276   18 1316  587  245  446  978 1002 1631
  341 1307  524 1267  103  242 1378 1328 1294 1309  724  197  999  547
 1100 1456   77 1506 1472  460   11 1420  218 1253  392  670 1321  100
 1205  443   92  811  774  159 1770  972 1157 1102  217  358 1473  440
  140 1361  481  512 1117  300 1263 1581  901 1298  310  637  758 1734
 1288  326 1678 1444 1344 1379  828  982  104  317 1529 1627  115  645
 1404  940 1305 1049 1645 1466  175 1165 1419 1031  581 1580  854  725
 1655 1134  569 1387 1381 1760  360 1735 1146 1411  969 1281  591  327
  466  667  147  109  784 1396 1349  839 1284  802   97  281 1382 1039
 1483  376 1249 1207 1213 1219 1345 1523  949 1063  983  886 1151  992
 1107 1314  151   69 1489  695  738  444 1525  825  506  518 1077 1354
  713  690  861 1389  968  421  907  205  856   72  651  161  867  971
 1078   64 1701  546 1216   27 1709  193 1528  957  577  346 1416  396
 1182  652 1083 1778  680 1754 1544 1703  636  472  453  463   75  756
  296  891  813  474  697]

In [298]:
train_df["Num_Bank_Accounts"].describe()

count   100,000.00
mean         17.09
std         117.40
min          -1.00
25%           3.00
50%           6.00
75%           7.00
max       1,798.00
Name: Num_Bank_Accounts, dtype: float64

## Interest rate

In [299]:
fast_feature_description(train_df["Interest_Rate"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Interest_Rate
Non-Null Count   Dtype
--------------   -----
100000 non-null  int64
dtypes: int64(1)
memory usage: 781.4 KB
None
------- Common values -------
(1750,)
[   3    6    8 ... 1347  387 5729]

In [300]:
train_df["Interest_Rate"].describe()

count   100,000.00
mean         72.47
std         466.42
min           1.00
25%           8.00
50%          13.00
75%          20.00
max       5,797.00
Name: Interest_Rate, dtype: float64

## Num of loan

In [301]:
fast_feature_description(train_df["Num_of_Loan"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Num_of_Loan
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(434,)
['4' '1' '3' '967' '-100' '0' '0_' '2' '3_' '2_' '7' '5' '5_' '6' '8' '8_'
 '9' '9_' '4_' '7_' '1_' '1464' '6_' '622' '352' '472' '1017' '945' '146'
 '563' '341' '444' '720' '1485' '49' '737' '1106' '466' '728' '313' '843'
 '597_' '617' '119' '663' '640' '92_' '1019' '501' '1302' '39' '716' '848'
 '931' '1214' '186' '424' '1001' '1110' '1152' '457' '1433' '1187' '52'
 '1480' '1047' '1035' '1347_' '33' '193' '699' '329' '1451' '484' '132'
 '649' '995' '545' '684' '1135' '1094' '1204' '654' '58' '348' '614'
 '1363' '323' '1406' '1348' '430' '153' '1461' '905' '1312' '1424' '1154'
 '95' '1353' '1228' '819' '1006' '795' '359' '1209' '590' '696' '1185_'
 '1465' '911' '1181' '70' '816' '1369' '143' '1416' '455' '55' '1096'
 '1474' '420' '1131' '904' '89' '1259' '527' '1241' '449' '983' '418'
 '319' '23' '238' '638' '138' '235_' '280' '1070' '1484' '274' '494'
 '1459_' '404' '1354' '1495' '1391' '601' '1313' '1319' '898' '231' '752'
 '174' '961' '1046' '834' '284' '438' '288' '1463' '1151' '719' '198'
 '1015' '855' '841' '392' '1444' '103' '1320_' '745' '172' '252' '630_'
 '241' '31' '405' '1217' '1030' '1257' '137' '157' '164' '1088' '1236'
 '777' '1048' '613' '330' '1439' '321' '661' '952' '939' '562' '1202'
 '302' '943' '394' '955' '1318' '936' '781' '100' '1329' '1365' '860'
 '217' '191' '32' '282' '351' '1387' '757' '416' '833' '359_' '292'
 '1225_' '1227' '639' '859' '243' '267' '510' '332' '996' '597' '311'
 '492' '820' '336' '123' '540' '131_' '1311_' '1441' '895' '891' '50'
 '940' '935' '596' '29' '1182' '1129_' '1014' '251' '365' '291' '1447'
 '742' '1085' '148' '462' '832' '881' '1225' '1412' '785_' '1127' '910'
 '538' '999' '733' '101' '237' '87' '659' '633' '387' '447' '629' '831'
 '1384' '773' '621' '1419' '289' '143_' '285' '1393' '1131_' '27_' '1359'
 '1482' '1189' '1294' '201' '579' '814' '141' '1320' '581' '1171_' '295'
 '290' '433' '679' '1040' '1054' '1430' '1023' '1077' '1457' '1150' '701'
 '1382' '889' '437' '372' '1222' '126' '1159' '868' '19' '1297' '227_'
 '190' '809' '1216' '1074' '571' '520' '1274' '1340' '991' '316' '697'
 '926' '873' '1002' '378_' '65' '875' '867' '548' '652' '1372' '606'
 '1036' '1300' '17' '1178' '802' '1219_' '1271' '1137' '1496' '439' '196'
 '636' '192' '228' '1053' '229' '753' '1296' '1371' '254' '863' '464'
 '515' '838' '1160' '1289' '1298' '799' '182' '574' '527_' '242' '415'
 '869' '958' '54' '1265' '656' '275' '778' '208' '147' '350' '507' '463'
 '497' '1129' '927' '653' '662' '529' '635' '1027_' '897' '1039' '227'
 '1345' '924' '696_' '1279' '546' '1112' '1210' '526' '300' '1103' '504'
 '136' '1400' '78' '686' '1091' '344' '215' '84' '628' '1470' '968' '1478'
 '83' '1196' '1307' '1132_' '1008' '917' '657' '56' '18' '41' '801' '978'
 '216' '349' '966']

In [302]:
train_df["Num_of_Loan"] = train_df["Num_of_Loan"].str.replace("_", "")
train_df["Num_of_Loan"] = train_df["Num_of_Loan"].astype(int)

train_df["Num_of_Loan"].describe()

count   100,000.00
mean          3.01
std          62.65
min        -100.00
25%           1.00
50%           3.00
75%           5.00
max       1,496.00
Name: Num_of_Loan, dtype: float64

## Delay from due date

In [303]:
fast_feature_description(train_df["Delay_from_due_date"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Delay_from_due_date
Non-Null Count   Dtype
--------------   -----
100000 non-null  int64
dtypes: int64(1)
memory usage: 781.4 KB
None
------- Common values -------
(73,)
[ 3 -1  5  6  8  7 13 10  0  4  9  1 12 11 30 31 34 27 14  2 -2 16 17 15
 23 22 21 18 19 52 51 48 53 26 43 28 25 20 47 46 49 24 61 29 50 58 45 59
 55 56 57 54 62 65 64 67 36 41 33 32 39 44 42 60 35 38 -3 63 40 37 -5 -4
 66]

In [304]:
train_df["Delay_from_due_date"].describe()

count   100,000.00
mean         21.07
std          14.86
min          -5.00
25%          10.00
50%          18.00
75%          28.00
max          67.00
Name: Delay_from_due_date, dtype: float64

## Change credit limit

In [305]:
fast_feature_description(train_df["Changed_Credit_Limit"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Changed_Credit_Limit
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(4384,)
['11.27' '_' '6.27' ... '17.509999999999998' '25.16' '21.17']

In [306]:
(train_df["Changed_Credit_Limit"] == "_").mean()

np.float64(0.02091)

In [307]:
train_df["Changed_Credit_Limit"] = train_df["Changed_Credit_Limit"].str.replace(
    "_", "0"
)
train_df["Changed_Credit_Limit"] = train_df["Changed_Credit_Limit"].astype(float)

train_df["Changed_Credit_Limit"].describe()

count   100,000.00
mean         10.17
std           6.88
min          -6.49
25%           4.97
50%           9.25
75%          14.66
max          36.97
Name: Changed_Credit_Limit, dtype: float64

## Num Credit Inquiries

In [308]:
fast_feature_description(train_df["Num_Credit_Inquiries"])

------- NULL VALUES --------
1965
0.01965
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Num_Credit_Inquiries
Non-Null Count  Dtype
--------------  -----
98035 non-null  float64
dtypes: float64(1)
memory usage: 781.4 KB
None
------- Common values -------
(1224,)
[   4.    2.    3. ... 1361.  310.   74.]

In [309]:
train_df["Num_Credit_Inquiries"].describe()

count   98,035.00
mean        27.75
std        193.18
min          0.00
25%          3.00
50%          6.00
75%          9.00
max      2,597.00
Name: Num_Credit_Inquiries, dtype: float64

## Outstanding Debt

In [310]:
fast_feature_description(train_df["Outstanding_Debt"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Outstanding_Debt
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(13178,)
['809.98' '605.03' '1303.01' ... '3571.7_' '3571.7' '502.38']

In [311]:
train_df["Outstanding_Debt"] = train_df["Outstanding_Debt"].str.replace("_", "")
train_df["Outstanding_Debt"] = train_df["Outstanding_Debt"].astype(float)

train_df["Outstanding_Debt"].describe()

count   100,000.00
mean      1,426.22
std       1,155.13
min           0.23
25%         566.07
50%       1,166.15
75%       1,945.96
max       4,998.07
Name: Outstanding_Debt, dtype: float64

## Credit_Utilization_Ratio

In [312]:
fast_feature_description(train_df["Credit_Utilization_Ratio"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Credit_Utilization_Ratio
Non-Null Count   Dtype
--------------   -----
100000 non-null  float64
dtypes: float64(1)
memory usage: 781.4 KB
None
------- Common values -------
(100000,)
[26.82261962 31.94496006 28.60935202 ... 41.25552226 33.63820798
 34.19246265]

In [313]:
train_df["Credit_Utilization_Ratio"].describe()

count   100,000.00
mean         32.29
std           5.12
min          20.00
25%          28.05
50%          32.31
75%          36.50
max          50.00
Name: Credit_Utilization_Ratio, dtype: float64

## Credit_History_Age

In [314]:
fast_feature_description(train_df["Credit_History_Age"])

------- NULL VALUES --------
9030
0.0903
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Credit_History_Age
Non-Null Count  Dtype
--------------  -----
90970 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(405,)
['22 Years and 1 Months' nan '22 Years and 3 Months'
 '22 Years and 4 Months' '22 Years and 5 Months' '22 Years and 6 Months'
 '22 Years and 7 Months' '26 Years and 7 Months' '26 Years and 8 Months'
 '26 Years and 9 Months' '26 Years and 10 Months' '26 Years and 11 Months'
 '27 Years and 0 Months' '27 Years and 1 Months' '27 Years and 2 Months'
 '17 Years and 9 Months' '17 Years and 10 Months' '17 Years and 11 Months'
 '18 Years and 1 Months' '18 Years and 2 Months' '18 Years and 3 Months'
 '18 Years and 4 Months' '17 Years and 3 Months' '17 Years and 4 Months'
 '17 Years and 5 Months' '17 Years and 6 Months' '17 Years and 7 Months'
 '17 Years and 8 Months' '30 Years and 8 Months' '30 Years and 9 Months'
 '30 Years and 10 Months' '30 Years and 11 Months' '31 Years and 0 Months'
 '31 Years and 1 Months' '31 Years and 2 Months' '31 Years and 3 Months'
 '32 Years and 0 Months' '32 Years and 2 Months' '32 Years and 3 Months'
 '32 Years and 5 Months' '32 Years and 6 Months' '30 Years and 7 Months'
 '14 Years and 8 Months' '14 Years and 9 Months' '14 Years and 10 Months'
 '14 Years and 11 Months' '15 Years and 0 Months' '15 Years and 1 Months'
 '15 Years and 2 Months' '21 Years and 4 Months' '21 Years and 5 Months'
 '21 Years and 6 Months' '21 Years and 7 Months' '21 Years and 8 Months'
 '21 Years and 9 Months' '21 Years and 10 Months' '21 Years and 11 Months'
 '26 Years and 6 Months' '19 Years and 2 Months' '19 Years and 3 Months'
 '19 Years and 4 Months' '19 Years and 5 Months' '19 Years and 6 Months'
 '19 Years and 7 Months' '19 Years and 8 Months' '25 Years and 5 Months'
 '25 Years and 6 Months' '25 Years and 7 Months' '25 Years and 8 Months'
 '25 Years and 9 Months' '25 Years and 10 Months' '25 Years and 11 Months'
 '26 Years and 0 Months' '27 Years and 3 Months' '27 Years and 4 Months'
 '27 Years and 5 Months' '8 Years and 11 Months' '9 Years and 0 Months'
 '9 Years and 1 Months' '9 Years and 2 Months' '9 Years and 3 Months'
 '9 Years and 4 Months' '9 Years and 6 Months' '18 Years and 5 Months'
 '18 Years and 6 Months' '18 Years and 8 Months' '18 Years and 9 Months'
 '16 Years and 10 Months' '16 Years and 11 Months' '17 Years and 0 Months'
 '17 Years and 1 Months' '17 Years and 2 Months' '29 Years and 2 Months'
 '29 Years and 3 Months' '29 Years and 4 Months' '29 Years and 6 Months'
 '29 Years and 8 Months' '29 Years and 9 Months' '6 Years and 5 Months'
 '6 Years and 6 Months' '6 Years and 7 Months' '6 Years and 8 Months'
 '6 Years and 9 Months' '6 Years and 10 Months' '6 Years and 11 Months'
 '7 Years and 0 Months' '27 Years and 6 Months' '27 Years and 7 Months'
 '27 Years and 8 Months' '27 Years and 9 Months' '18 Years and 7 Months'
 '19 Years and 9 Months' '19 Years and 10 Months' '10 Years and 1 Months'
 '10 Years and 2 Months' '10 Years and 3 Months' '10 Years and 4 Months'
 '10 Years and 5 Months' '10 Years and 6 Months' '10 Years and 7 Months'
 '10 Years and 8 Months' '32 Years and 9 Months' '32 Years and 10 Months'
 '32 Years and 11 Months' '33 Years and 0 Months' '33 Years and 1 Months'
 '33 Years and 4 Months' '12 Years and 3 Months' '12 Years and 4 Months'
 '12 Years and 5 Months' '12 Years and 6 Months' '12 Years and 7 Months'
 '12 Years and 8 Months' '12 Years and 10 Months' '12 Years and 9 Months'
 '13 Years and 8 Months' '13 Years and 11 Months' '14 Years and 0 Months'
 '14 Years and 1 Months' '14 Years and 2 Months' '14 Years and 3 Months'
 '30 Years and 3 Months' '30 Years and 4 Months' '30 Years and 5 Months'
 '30 Years and 6 Months' '8 Years and 9 Months' '8 Years and 10 Months'
 '18 Years and 10 Months' '18 Years and 11 Months' '19 Years and 0 Months'
 '19 Years and 1 Months' '8 Years and 8 Months' '13 Years and 1 Months'
 '13 Years and 2 Months' '13 Years and 3 Months' '13 Years and 5 Months'
 '13 Years and 6 Months' '13 Years and 7 Months' '22 Years and 0 Months'
 '26 Years and 1 Months' '26 Years and 2 Months' '13 Years and 4 Months'
 '13 Years and 9 Months' '27 Years and 11 Months' '28 Years and 0 Months'
 '28 Years and 1 Months' '28 Years and 2 Months' '28 Years and 3 Months'
 '28 Years and 4 Months' '28 Years and 5 Months' '28 Years and 6 Months'
 '7 Years and 10 Months' '7 Years and 11 Months' '8 Years and 0 Months'
 '8 Years and 1 Months' '8 Years and 2 Months' '8 Years and 3 Months'
 '8 Years and 4 Months' '8 Years and 5 Months' '24 Years and 3 Months'
 '24 Years and 4 Months' '24 Years and 5 Months' '24 Years and 6 Months'
 '24 Years and 7 Months' '24 Years and 8 Months' '24 Years and 9 Months'
 '1 Years and 2 Months' '1 Years and 3 Months' '1 Years and 4 Months'
 '1 Years and 5 Months' '1 Years and 6 Months' '1 Years and 7 Months'
 '1 Years and 8 Months' '10 Years and 11 Months' '11 Years and 0 Months'
 '11 Years and 1 Months' '11 Years and 2 Months' '11 Years and 3 Months'
 '11 Years and 4 Months' '11 Years and 5 Months' '11 Years and 6 Months'
 '19 Years and 11 Months' '20 Years and 0 Months' '20 Years and 1 Months'
 '10 Years and 9 Months' '10 Years and 10 Months' '14 Years and 4 Months'
 '14 Years and 5 Months' '14 Years and 6 Months' '20 Years and 8 Months'
 '20 Years and 9 Months' '20 Years and 10 Months' '20 Years and 11 Months'
 '21 Years and 0 Months' '21 Years and 1 Months' '21 Years and 2 Months'
 '21 Years and 3 Months' '0 Years and 4 Months' '0 Years and 5 Months'
 '0 Years and 6 Months' '0 Years and 8 Months' '0 Years and 9 Months'
 '0 Years and 10 Months' '31 Years and 7 Months' '31 Years and 8 Months'
 '31 Years and 9 Months' '31 Years and 10 Months' '31 Years and 11 Months'
 '32 Years and 1 Months' '12 Years and 11 Months' '13 Years and 0 Months'
 '27 Years and 10 Months' '11 Years and 7 Months' '11 Years and 8 Months'
 '11 Years and 9 Months' '11 Years and 10 Months' '24 Years and 10 Months'
 '24 Years and 11 Months' '25 Years and 0 Months' '25 Years and 1 Months'
 '25 Years and 2 Months' '25 Years and 3 Months' '18 Years and 0 Months'
 '31 Years and 4 Months' '31 Years and 5 Months' '31 Years and 6 Months'
 '5 Years and 2 Months' '5 Years and 3 Months' '5 Years and 4 Months'
 '5 Years and 5 Months' '5 Years and 6 Months' '5 Years and 7 Months'
 '5 Years and 8 Months' '5 Years and 9 Months' '2 Years and 11 Months'
 '3 Years and 0 Months' '3 Years and 1 Months' '3 Years and 2 Months'
 '3 Years and 3 Months' '3 Years and 4 Months' '3 Years and 5 Months'
 '3 Years and 6 Months' '16 Years and 4 Months' '16 Years and 5 Months'
 '16 Years and 6 Months' '16 Years and 7 Months' '16 Years and 8 Months'
 '16 Years and 9 Months' '22 Years and 11 Months' '23 Years and 0 Months'
 '23 Years and 2 Months' '23 Years and 3 Months' '23 Years and 4 Months'
 '23 Years and 5 Months' '23 Years and 6 Months' '8 Years and 6 Months'
 '8 Years and 7 Months' '4 Years and 5 Months' '4 Years and 6 Months'
 '4 Years and 7 Months' '4 Years and 8 Months' '4 Years and 9 Months'
 '4 Years and 10 Months' '4 Years and 11 Months' '5 Years and 0 Months'
 '32 Years and 8 Months' '33 Years and 2 Months' '33 Years and 3 Months'
 '12 Years and 2 Months' '32 Years and 4 Months' '29 Years and 11 Months'
 '30 Years and 0 Months' '30 Years and 2 Months' '26 Years and 3 Months'
 '26 Years and 4 Months' '26 Years and 5 Months' '7 Years and 6 Months'
 '7 Years and 7 Months' '7 Years and 8 Months' '7 Years and 9 Months'
 '28 Years and 7 Months' '28 Years and 8 Months' '28 Years and 9 Months'
 '28 Years and 10 Months' '29 Years and 5 Months' '29 Years and 7 Months'
 '20 Years and 2 Months' '20 Years and 3 Months' '20 Years and 4 Months'
 '20 Years and 5 Months' '20 Years and 6 Months' '20 Years and 7 Months'
 '28 Years and 11 Months' '29 Years and 0 Months' '13 Years and 10 Months'
 '1 Years and 9 Months' '1 Years and 10 Months' '1 Years and 11 Months'
 '33 Years and 5 Months' '33 Years and 6 Months' '33 Years and 7 Months'
 '33 Years and 8 Months' '29 Years and 1 Months' '5 Years and 1 Months'
 '5 Years and 10 Months' '5 Years and 11 Months' '6 Years and 0 Months'
 '6 Years and 1 Months' '6 Years and 2 Months' '6 Years and 3 Months'
 '22 Years and 9 Months' '22 Years and 10 Months' '23 Years and 1 Months'
 '22 Years and 2 Months' '15 Years and 4 Months' '15 Years and 5 Months'
 '15 Years and 6 Months' '15 Years and 7 Months' '15 Years and 8 Months'
 '15 Years and 9 Months' '15 Years and 10 Months' '15 Years and 11 Months'
 '2 Years and 3 Months' '2 Years and 4 Months' '2 Years and 5 Months'
 '2 Years and 6 Months' '2 Years and 7 Months' '2 Years and 8 Months'
 '2 Years and 9 Months' '2 Years and 10 Months' '2 Years and 0 Months'
 '16 Years and 2 Months' '16 Years and 3 Months' '22 Years and 8 Months'
 '9 Years and 5 Months' '9 Years and 7 Months' '9 Years and 8 Months'
 '9 Years and 9 Months' '11 Years and 11 Months' '12 Years and 0 Months'
 '12 Years and 1 Months' '24 Years and 2 Months' '16 Years and 0 Months'
 '16 Years and 1 Months' '14 Years and 7 Months' '25 Years and 4 Months'
 '15 Years and 3 Months' '7 Years and 1 Months' '7 Years and 2 Months'
 '7 Years and 3 Months' '7 Years and 4 Months' '7 Years and 5 Months'
 '23 Years and 7 Months' '23 Years and 8 Months' '23 Years and 9 Months'
 '30 Years and 1 Months' '29 Years and 10 Months' '9 Years and 10 Months'
 '9 Years and 11 Months' '10 Years and 0 Months' '2 Years and 2 Months'
 '23 Years and 10 Months' '23 Years and 11 Months' '24 Years and 0 Months'
 '24 Years and 1 Months' '6 Years and 4 Months' '0 Years and 1 Months'
 '0 Years and 2 Months' '0 Years and 3 Months' '0 Years and 7 Months'
 '3 Years and 8 Months' '32 Years and 7 Months' '3 Years and 7 Months'
 '3 Years and 9 Months' '3 Years and 10 Months' '0 Years and 11 Months'
 '1 Years and 0 Months' '1 Years and 1 Months' '4 Years and 4 Months'
 '3 Years and 11 Months' '4 Years and 0 Months' '4 Years and 1 Months'
 '4 Years and 2 Months' '4 Years and 3 Months' '2 Years and 1 Months']

In [315]:
def parse_credit_history(x):
    if pd.isna(x):
        return np.nan

    try:
        parts = x.split()
        years = int(parts[0])
        months = int(parts[3])
        return years + months / 12
    except:
        return np.nan

In [316]:
train_df["Credit_History_Age"] = train_df["Credit_History_Age"].apply(
    parse_credit_history
)
train_df["Credit_History_Age"].describe()

count   90,970.00
mean        18.43
std          8.31
min          0.08
25%         12.00
50%         18.25
75%         25.17
max         33.67
Name: Credit_History_Age, dtype: float64

## Total_EMI_per_month

In [317]:
fast_feature_description(train_df["Total_EMI_per_month"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Total_EMI_per_month
Non-Null Count   Dtype
--------------   -----
100000 non-null  float64
dtypes: float64(1)
memory usage: 781.4 KB
None
------- Common values -------
(14950,)
[4.95749492e+01 1.88162146e+01 2.46992319e+02 ... 1.21120000e+04
 3.51040226e+01 5.86380000e+04]

## Amount_invested_monthly

In [318]:
fast_feature_description(train_df["Amount_invested_monthly"])

------- NULL VALUES --------
4479
0.04479
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Amount_invested_monthly
Non-Null Count  Dtype
--------------  -----
95521 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(91050,)
['80.41529543900253' '118.28022162236736' '81.699521264648' ...
 '24.02847744864441' '251.67258219721603' '167.1638651610451']

In [319]:
train_df["Amount_invested_monthly"] = train_df["Amount_invested_monthly"].str.replace(
    "_", ""
)
train_df["Amount_invested_monthly"] = train_df["Amount_invested_monthly"].astype(float)

train_df["Amount_invested_monthly"].describe()

count   95,521.00
mean       637.41
std      2,043.32
min          0.00
25%         74.53
50%        135.93
75%        265.73
max     10,000.00
Name: Amount_invested_monthly, dtype: float64

## Monthly_Balance

In [320]:
fast_feature_description(train_df["Monthly_Balance"])

------- NULL VALUES --------
1200
0.012
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Monthly_Balance
Non-Null Count  Dtype
--------------  -----
98800 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(98793,)
['312.49408867943663' '284.62916249607184' '331.2098628537912' ...
 516.8090832742814 319.1649785257098 393.6736955618808]

In [321]:
train_df["Monthly_Balance"] = train_df["Monthly_Balance"].str.replace("_", "")
train_df["Monthly_Balance"] = train_df["Monthly_Balance"].astype(float)

train_df["Amount_invested_monthly"].describe()

count   95,521.00
mean       637.41
std      2,043.32
min          0.00
25%         74.53
50%        135.93
75%        265.73
max     10,000.00
Name: Amount_invested_monthly, dtype: float64

## Num_of_Delayed_Payment

In [322]:
fast_feature_description(train_df["Num_of_Delayed_Payment"])

------- NULL VALUES --------
7002
0.07002
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Num_of_Delayed_Payment
Non-Null Count  Dtype
--------------  -----
92998 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(750,)
['7' nan '4' '8_' '6' '1' '-1' '3_' '0' '8' '5' '3' '9' '12' '15' '17'
 '10' '2' '2_' '11' '14' '20' '22' '13' '13_' '14_' '16' '12_' '18' '19'
 '23' '24' '21' '3318' '3083' '22_' '1338' '4_' '26' '11_' '3104' '21_'
 '25' '10_' '183_' '9_' '1106' '834' '19_' '24_' '17_' '23_' '2672' '20_'
 '2008' '-3' '538' '6_' '1_' '16_' '27' '-2' '3478' '2420' '15_' '707'
 '708' '26_' '18_' '3815' '28' '5_' '1867' '2250' '1463' '25_' '7_' '4126'
 '2882' '1941' '2655' '2628' '132' '3069' '306' '0_' '3539' '3684' '1823'
 '4128' '1946' '827' '2297' '2566' '904' '182' '929' '3568' '2503' '1552'
 '2812' '1697' '3764' '851' '3905' '923' '88' '1668' '3253' '808' '2689'
 '3858' '642' '3457' '1402' '1732' '3154' '847' '3037' '2204' '3103'
 '1063' '2056' '1282' '1841' '2569_' '211' '793' '3484' '411' '3491'
 '2072' '3050' '1049' '2162' '3402' '2753' '27_' '1718' '1014' '3260'
 '3855' '84' '2311' '3251' '1832' '4069' '3010' '733' '4241' '166' '2461'
 '1749' '3200' '663_' '2185' '4161' '3009' '359' '2015' '1523' '594'
 '1079' '1199' '186' '1015' '1989' '281' '559' '2165' '1509' '3545' '779'
 '192' '4311' '-2_' '2323' '1471' '1538' '3529' '439' '3456' '3040' '2697'
 '3179' '1332' '3175' '3112' '829' '4022' '3870' '4023' '531' '1511'
 '3092' '3191' '2400' '3621' '3536' '544' '1864' '28_' '142' '2300' '264'
 '72' '497' '398' '2222' '3960' '1473' '3043' '4216' '2903' '2658' '-1_'
 '4042' '1323_' '2184' '921' '1328' '3404' '2438' '809' '47' '1996' '4164'
 '1370' '1204' '2167' '4011' '2590' '2594' '2533' '1663' '1018' '2919'
 '3458' '3316' '2589' '2801' '3355' '2529' '2488' '4266' '1243' '739'
 '845' '4107' '1884' '337' '2660' '290' '674' '2450' '3738' '1792' '2823'
 '2570' '775' '960' '482' '1706' '2493' '3623' '3031' '2794_' '2219_'
 '758_' '1849' '3559' '4096' '3726' '1953' '2657' '4043' '2938' '4384'
 '1647' '2694' '3533' '519' '2677' '2413' '-3_' '4139' '2609' '4326'
 '4211' '823' '3011' '1608' '2860' '4219' '4047' '1531' '742' '52' '4024'
 '1673' '49' '2243' '1685' '1869' '2587' '3489' '749' '1164' '2616' '848_'
 '4134' '1530' '1502' '4075' '3845' '1060' '2573' '2128' '328' '640'
 '2585' '2230' '1795' '1180' '1534' '3739' '3313' '4191' '996' '372'
 '3340' '3177' '602' '787' '4135' '3878' '4059' '1218' '4051' '1766'
 '1359' '3107' '585' '1263' '2511' '709' '3632' '4077' '2943' '2793'
 '3245' '2317' '1640' '2237_' '3819' '252' '3978' '1498' '1833' '2737'
 '1192' '1481' '700' '271' '2286' '273' '1215' '3944' '2070' '1478' '3749'
 '871' '2508' '2959' '130' '294' '3097_' '3511' '415' '2196' '2138' '2149'
 '1874' '1553' '3847' '3222' '1222' '2907' '3051' '98' '1598' '416' '2314'
 '2955' '1691' '1450' '2021' '1636' '80' '3708' '195' '320' '2945' '1911'
 '3416' '3796' '4159' '2255' '938' '4397' '3776' '2148' '1994' '853'
 '1178' '1633' '196' '3864' '714' '1687' '1034' '468' '1337' '2044' '1541'
 '3661' '1211' '2645' '2007' '102' '1891' '3162' '3142' '2566_' '2766'
 '3881' '2728' '2671' '1952' '3580' '2705' '4251' '3840_' '972' '3119'
 '3502' '4185' '2954' '683' '1614' '1572' '4302' '3447' '1852' '2131'
 '1900' '1699' '133' '2018' '2127' '508' '210' '577' '1664' '2604' '1411'
 '2351' '867' '1371' '2352' '1191' '905' '4053' '3869' '933' '3660' '3300'
 '3629' '3208' '2142' '2521' '450' '583' '876' '121' '3919' '2560' '2578'
 '2060' '813' '1236' '1489' '4360' '1154' '2544' '4172' '2924' '426'
 '4270' '2768' '3909' '3951' '2712' '2498' '3171' '1750' '197' '2569'
 '265' '4293' '887' '2707' '2397' '4337' '4249' '2751' '2950' '1859' '107'
 '2348' '2506' '2810' '2873' '1301' '2262' '1890' '3078' '3865' '3268'
 '2777' '3105' '1278' '3793' '2276' '2879' '4298' '2141' '223' '2239'
 '846' '1862' '2756' '1181' '1184' '2617' '3972' '2334' '3900' '2759'
 '4169' '2280' '2492' '2729' '3750' '1825' '309' '2431' '3099' '2080'
 '2279' '2666' '3722' '1976' '529' '1985' '3060' '4278' '3212' '46' '3148'
 '3467' '4231' '3790' '473' '1536' '3955' '2324' '2381' '1177' '371'
 '2896' '3880' '2991' '4319' '1061' '662' '4144' '693' '2006' '3115'
 '2278_' '3751' '1861' '4262' '2913' '2615' '3492' '800' '3766' '384'
 '3407' '1087' '3329' '1086' '2216' '1087_' '2457' '3522' '3274' '3488'
 '2854' '238' '351' '3706' '4280' '4095' '2926' '1329' '3370' '283' '1392'
 '1743' '2429' '974' '3156' '1133' '4388' '3243' '4282' '2523' '4281'
 '3415' '2001' '441' '94' '3499' '969' '3368' '106' '1004' '2638' '3946'
 '2956' '4324' '85' '4113' '819' '615' '1172' '2553' '1765' '3495' '2820'
 '4239' '4340' '1295_' '2636' '4295' '1653' '1325' '1879' '1096' '1735'
 '3584' '1073' '1975' '3827' '2552' '3754' '2378' '532' '926' '2376'
 '3636' '3763' '778' '2621' '804' '754' '2418' '4019' '3926' '3861_'
 '3574' '175' '162' '2834' '3765' '2354' '523' '2274' '1606' '1443' '1354'
 '2142_' '1422' '2278' '1045' '4106' '3155' '666' '659' '3229' '1216'
 '2076' '1473_' '2384' '1954' '719' '2534' '4002' '541' '2875' '4344'
 '2081' '3894' '1256' '676' '4178' '399' '86' '1571' '4037' '1967' '4005'
 '3216' '1150' '2591' '1801' '3721' '1775' '2260' '3707' '4292' '1820'
 '145' '1480' '1850' '430' '217' '3920_' '1389' '1579' '3391' '2385'
 '3336' '3392' '3688' '221' '2047']

In [323]:
train_df["Num_of_Delayed_Payment"] = train_df["Num_of_Delayed_Payment"].str.replace(
    "_", ""
)
train_df["Num_of_Delayed_Payment"] = train_df["Num_of_Delayed_Payment"].astype(float)

train_df["Num_of_Delayed_Payment"].describe()

count   92,998.00
mean        30.92
std        226.03
min         -3.00
25%          9.00
50%         14.00
75%         18.00
max      4,397.00
Name: Num_of_Delayed_Payment, dtype: float64

# Categorical Variables

In [324]:
categorical_variables = [
    "Occupation",
    "Type_of_Loan",
    "Credit_Mix",
    "Payment_Behaviour",
    "Payment_of_Min_Amount",
]

In [325]:
train_df[categorical_variables]

,Occupation,Type_of_Loan,Credit_Mix,Payment_Behaviour,Payment_of_Min_Amount
0,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",_,High_spent_Small_value_payments,No
1,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Large_value_payments,No
2,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Medium_value_payments,No
3,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Small_value_payments,No
4,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,High_spent_Medium_value_payments,No
...,...,...,...,...,...
99995,Mechanic,"Auto Loan, and Student Loan",_,High_spent_Large_value_payments,No
99996,Mechanic,"Auto Loan, and Student Loan",_,High_spent_Medium_value_payments,No
99997,Mechanic,"Auto Loan, and Student Loan",Good,High_spent_Large_value_payments,No
99998,Mechanic,"Auto Loan, and Student Loan",Good,Low_spent_Large_value_payments,No
99999,Mechanic,"Auto Loan, and Student Loan",Good,!@9#%8,No

In [326]:
remaining_cols = (
    set(train_df.columns)
    - set(numeric_variables)
    - set(categorical_variables)
    - set(ids)
)
remaining_cols

{'Credit_Score', 'ID', 'Month', 'Name', 'Num_Credit_Card', 'SSN', 'avg_salary'}

## Occupation

In [327]:
fast_feature_description(train_df["Occupation"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Occupation
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(16,)
['Scientist' '_______' 'Teacher' 'Engineer' 'Entrepreneur' 'Developer'
 'Lawyer' 'Media_Manager' 'Doctor' 'Journalist' 'Manager' 'Accountant'
 'Musician' 'Mechanic' 'Writer' 'Architect']

In [328]:
train_df["Occupation"].value_counts()

Occupation
_______          7062
Lawyer           6575
Architect        6355
Engineer         6350
Scientist        6299
Mechanic         6291
Accountant       6271
Developer        6235
Media_Manager    6232
Teacher          6215
Entrepreneur     6174
Doctor           6087
Journalist       6085
Manager          5973
Musician         5911
Writer           5885
Name: count, dtype: int64

## Type_of_Loan

In [329]:
fast_feature_description(train_df["Type_of_Loan"])

------- NULL VALUES --------
11408
0.11408
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Type_of_Loan
Non-Null Count  Dtype
--------------  -----
88592 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(6261,)
['Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan'
 'Credit-Builder Loan' 'Auto Loan, Auto Loan, and Not Specified' ...
 'Home Equity Loan, Auto Loan, Auto Loan, and Auto Loan'
 'Payday Loan, Student Loan, Mortgage Loan, and Not Specified'
 'Personal Loan, Auto Loan, Mortgage Loan, Student Loan, and Student Loan']

In [330]:
train_df["Type_of_Loan"].nunique()

6260

In [332]:
a = train_df["Type_of_Loan"].iloc[0]
a = a.replace("and", "")
a = a.split(",")
a = [x.strip() for x in a]
a

['Auto Loan', 'Credit-Builder Loan', 'Personal Loan', 'Home Equity Loan']

In [333]:
def clean_loans(a):

    if pd.isna(a):

        return []

    return [loan.strip() for loan in a.replace("and", "").split(",")]

In [334]:
train_df["Type_of_Loan"] = train_df["Type_of_Loan"].apply(clean_loans)

In [338]:
unique_loans = set()

for loans in train_df["Type_of_Loan"]:
    unique_loans.update(loans)

unique_loans

{'Auto Loan',
 'Credit-Builder Loan',
 'Debt Consolidation Loan',
 'Home Equity Loan',
 'Mortgage Loan',
 'Not Specified',
 'Payday Loan',
 'Personal Loan',
 'Student Loan'}

In [340]:
for loan in unique_loans:
    train_df[loan] = train_df["Type_of_Loan"].apply(lambda x: int(loan in x))

In [342]:
for loan in unique_loans:
    train_df[loan] = train_df["Type_of_Loan"].apply(lambda x: int(loan in x))

In [345]:
unique_loans = list(unique_loans)
train_df[unique_loans]

,Payday Loan,Credit-Builder Loan,Auto Loan,Student Loan,Personal Loan,Not Specified,Home Equity Loan,Debt Consolidation Loan,Mortgage Loan
0,0,1,1,0,1,0,1,0,0
1,0,1,1,0,1,0,1,0,0
2,0,1,1,0,1,0,1,0,0
3,0,1,1,0,1,0,1,0,0
4,0,1,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...
99995,0,0,1,1,0,0,0,0,0
99996,0,0,1,1,0,0,0,0,0
99997,0,0,1,1,0,0,0,0,0
99998,0,0,1,1,0,0,0,0,0
99999,0,0,1,1,0,0,0,0,0

## Credit_Mix

In [348]:
fast_feature_description(train_df["Credit_Mix"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Credit_Mix
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(4,)
['_' 'Good' 'Standard' 'Bad']

In [350]:
train_df["Credit_Mix"].value_counts(normalize=True)

Credit_Mix
Standard   0.36
Good       0.24
_          0.20
Bad        0.19
Name: proportion, dtype: float64

## Payment_Behaviour

In [356]:
fast_feature_description(train_df["Payment_Behaviour"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Payment_Behaviour
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(7,)
['High_spent_Small_value_payments' 'Low_spent_Large_value_payments'
 'Low_spent_Medium_value_payments' 'Low_spent_Small_value_payments'
 'High_spent_Medium_value_payments' '!@9#%8'
 'High_spent_Large_value_payments']

In [358]:
train_df["Payment_Behaviour"].value_counts(normalize=True)

Payment_Behaviour
Low_spent_Small_value_payments     0.26
High_spent_Medium_value_payments   0.18
Low_spent_Medium_value_payments    0.14
High_spent_Large_value_payments    0.14
High_spent_Small_value_payments    0.11
Low_spent_Large_value_payments     0.10
!@9#%8                             0.08
Name: proportion, dtype: float64

## Payment_of_Min_Amount

In [360]:
fast_feature_description(train_df["Payment_of_Min_Amount"])

------- NULL VALUES --------
0
0.0
------- INFO -------
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Payment_of_Min_Amount
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
------- Common values -------
(3,)
['No' 'NM' 'Yes']

In [361]:
train_df["Payment_of_Min_Amount"].value_counts()

Payment_of_Min_Amount
Yes    52326
No     35667
NM     12007
Name: count, dtype: int64

In [365]:
train_df[train_df["Payment_of_Min_Amount"] == "NM"]

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,num_month,avg_salary,Payday Loan,Credit-Builder Loan,Auto Loan,Student Loan,Personal Loan,Not Specified,Home Equity Loan,Debt Consolidation Loan,Mortgage Loan
14,0x1614,CUS_0x21b1,July,Rick Rothackerj,28,004-07-5839,Teacher,"34,847.84",NaN,2,4,6,1,[Credit-Builder Loan],3,4.00,5.42,2.00,Good,605.03,31.13,27.08,NM,18.82,70.10,High_spent_Medium_value_payments,464.88,Good,202207,NaN,0,1,0,0,0,0,0,0,0
26,0x1628,CUS_0xb891,March,Jasond,55,072-31-6145,Entrepreneur,"30,689.89","2,612.49",2,5,4,1,[Not Specified],3,9.00,1.99,4.00,Good,632.46,32.30,17.42,NM,16.42,83.41,High_spent_Medium_value_payments,411.43,Standard,202203,11.75,0,0,0,0,0,1,0,0,0
33,0x1633,CUS_0x1cdb,February,Deepaa,21,615-06-7821,Developer,"35,547.71",NaN,7,5,5,0,[],9,NaN,2.58,4.00,Standard,943.86,27.02,30.75,NM,0.00,74.44,High_spent_Medium_value_payments,460.89,Standard,202202,NaN,0,0,0,0,0,0,0,0,0
41,0x163f,CUS_0x95ee,February,Np,31,612-70-8987,_______,"73,928.46","5,988.71",4,5,8,0,[],8,7.00,10.14,2.00,Good,548.20,42.77,32.00,NM,0.00,172.94,Low_spent_Medium_value_payments,705.93,Good,202202,12.34,0,0,0,0,0,0,0,0,0
48,0x164a,CUS_0x284a,January,Nadiaq,33,411-51-0676,Lawyer,"131,313.40","11,242.78",0,1,8,2,"[Credit-Builder Loan, Mortgage Loan]",0,3.00,9.34,2.00,Good,352.16,32.20,30.58,NM,137.64,378.17,High_spent_Medium_value_payments,858.46,Good,202201,11.68,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99939,0x25f95,CUS_0xad4f,April,Sabina Zawadzkig,47,226-45-0652,Developer,"22,620.79","1,722.07",7,3,9,0,[],27,19.00,5.31,2.00,_,642.46,26.73,29.50,NM,0.00,205.76,Low_spent_Small_value_payments,NaN,Poor,202204,13.14,0,0,0,0,0,0,0,0,0
99949,0x25fa3,CUS_0x51b3,June,Ryana,33,837-85-9800,Media_Manager,"59,146.36","4,908.86",3,6,6,1,[Personal Loan],6,6.00,6.68,5.00,Good,418.03,24.98,20.50,NM,26.78,91.32,High_spent_Medium_value_payments,NaN,Standard,202206,12.05,0,0,0,0,1,0,0,0,0
99968,0x25fc2,CUS_0xf16,January,Maria Sheahanb,44,#F%$D@*&8,Media_Manager,"16,680.35","1,528.03",1,1,5,4,"[Payday Loan, Student Loan, Mortgage Loan, Not...",4,0.00,5.69,4.00,Good,897.16,39.87,NaN,NM,41.11,52.95,High_spent_Small_value_payments,NaN,Good,202201,10.92,1,0,0,1,0,1,0,0,1
99979,0x25fd1,CUS_0xaf61,April,Chris Wickhamm,49,133-16-7738,Writer,"37,188.10","3,097.01",1,4,5,3,"[Home Equity Loan, Mortgage Loan, Student Loan]",3,12.00,5.38,3.00,Good,620.64,36.98,30.00,NM,84.21,215.49,Low_spent_Small_value_payments,NaN,Good,202204,12.01,0,0,0,1,0,0,1,0,1
99981,0x25fd3,CUS_0xaf61,June,Chris Wickhamm,50,133-16-7738,Writer,"37,188.10","3,097.01",1,4,5,3,"[Home Equity Loan, Mortgage Loan, Student Loan]",5,12.00,5.38,3.00,Good,620.64,37.75,30.17,NM,84.21,147.34,Low_spent_Small_value_payments,NaN,Good,202206,12.01,0,0,0,1,0,0,1,0,1

In [368]:
pd.crosstab(train_df["Month"], train_df["Payment_of_Min_Amount"])

Payment_of_Min_Amount    NM    No   Yes
Month
April                  1504  4433  6563
August                 1438  4491  6571
February               1501  4453  6546
January                1512  4464  6524
July                   1517  4469  6514
June                   1493  4468  6539
March                  1496  4432  6572
May                    1546  4457  6497